#!/usr/bin/env python
# -*- coding: utf-8 -*-
__author__ = 'g4idrijs'
import time
a1=[([0]* 100) for i in xrange(100)]
b1=[([0]* 100) for i in xrange(100)]
c1=[([0]* 100) for i in xrange(100)]

begin1 = time.clock()
for i in xrange(100):
    for j in xrange(100):
        for k in xrange(100):
            c1[i][j]+=a1[i][k]*b1[k][j]
end1 = time.clock()

print u"用时 %f s" % (end1-begin1)

import numpy as np
a2=np.zeros((100,100),dtype = np.double)
b2=np.zeros((100,100),dtype = np.double)

begin2 = time.clock()
c2=np.dot(a2,b2)
end2 = time.clock()

print u"用时 %f s" % (end2-begin2)